package com.zy.atsm.dao;

import com.zy.atsm.entity.ProjectInfo;

import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ProjectInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_INFO
     *
     * @mbg.generated
     */
    int insert(ProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_INFO
     *
     * @mbg.generated
     */
    ProjectInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_INFO
     *
     * @mbg.generated
     */
    List<ProjectInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectInfo record);
}