package com.zy.atsm.dao;

import com.zy.atsm.entity.Report;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ReportDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated
     */
    List<Report> selectAll();
}