package com.zy.atsm.dao;

import com.zy.atsm.entity.StudentInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface StudentInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_INFO
     *
     * @mbg.generated
     */
    int insert(StudentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_INFO
     *
     * @mbg.generated
     */
    StudentInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_INFO
     *
     * @mbg.generated
     */
    List<StudentInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StudentInfo record);

    List selectById(Integer id);
}