package com.zy.atsm.dao;

import com.zy.atsm.entity.TeacherInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface TeacherInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER_INFO
     *
     * @mbg.generated
     */
    int insert(TeacherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER_INFO
     *
     * @mbg.generated
     */
    TeacherInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER_INFO
     *
     * @mbg.generated
     */
    List<TeacherInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherInfo record);
}