package com.zy.atsm.entity;

import java.io.Serializable;

public class Report implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.STUDENT_ID
     *
     * @mbg.generated
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.STUDENT_NAME
     *
     * @mbg.generated
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.PROJECT_ID
     *
     * @mbg.generated
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.PROJECT_NAME
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.CREDIT
     *
     * @mbg.generated
     */
    private String credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.REASON
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.PROOF
     *
     * @mbg.generated
     */
    private String proof;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table REPORT
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.ID
     *
     * @return the value of REPORT.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.ID
     *
     * @param id the value for REPORT.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.STUDENT_ID
     *
     * @return the value of REPORT.STUDENT_ID
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.STUDENT_ID
     *
     * @param studentId the value for REPORT.STUDENT_ID
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.STUDENT_NAME
     *
     * @return the value of REPORT.STUDENT_NAME
     *
     * @mbg.generated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.STUDENT_NAME
     *
     * @param studentName the value for REPORT.STUDENT_NAME
     *
     * @mbg.generated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.PROJECT_ID
     *
     * @return the value of REPORT.PROJECT_ID
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.PROJECT_ID
     *
     * @param projectId the value for REPORT.PROJECT_ID
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.PROJECT_NAME
     *
     * @return the value of REPORT.PROJECT_NAME
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.PROJECT_NAME
     *
     * @param projectName the value for REPORT.PROJECT_NAME
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.CREDIT
     *
     * @return the value of REPORT.CREDIT
     *
     * @mbg.generated
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.CREDIT
     *
     * @param credit the value for REPORT.CREDIT
     *
     * @mbg.generated
     */
    public void setCredit(String credit) {
        this.credit = credit == null ? null : credit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.REASON
     *
     * @return the value of REPORT.REASON
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.REASON
     *
     * @param reason the value for REPORT.REASON
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.PROOF
     *
     * @return the value of REPORT.PROOF
     *
     * @mbg.generated
     */
    public String getProof() {
        return proof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.PROOF
     *
     * @param proof the value for REPORT.PROOF
     *
     * @mbg.generated
     */
    public void setProof(String proof) {
        this.proof = proof == null ? null : proof.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentId=").append(studentId);
        sb.append(", studentName=").append(studentName);
        sb.append(", projectId=").append(projectId);
        sb.append(", projectName=").append(projectName);
        sb.append(", credit=").append(credit);
        sb.append(", reason=").append(reason);
        sb.append(", proof=").append(proof);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}