package com.zy.atsm.entity;

import java.io.Serializable;

public class StudentInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT_INFO.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT_INFO.STUDENT_NAME
     *
     * @mbg.generated
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT_INFO.STUDENT_PASSWORD
     *
     * @mbg.generated
     */
    private String studentPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT_INFO.DEPARMENT
     *
     * @mbg.generated
     */
    private String deparment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT_INFO.CLASS
     *
     * @mbg.generated
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT_INFO.SCORE
     *
     * @mbg.generated
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STUDENT_INFO
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT_INFO.ID
     *
     * @return the value of STUDENT_INFO.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT_INFO.ID
     *
     * @param id the value for STUDENT_INFO.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT_INFO.STUDENT_NAME
     *
     * @return the value of STUDENT_INFO.STUDENT_NAME
     *
     * @mbg.generated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT_INFO.STUDENT_NAME
     *
     * @param studentName the value for STUDENT_INFO.STUDENT_NAME
     *
     * @mbg.generated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT_INFO.STUDENT_PASSWORD
     *
     * @return the value of STUDENT_INFO.STUDENT_PASSWORD
     *
     * @mbg.generated
     */
    public String getStudentPassword() {
        return studentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT_INFO.STUDENT_PASSWORD
     *
     * @param studentPassword the value for STUDENT_INFO.STUDENT_PASSWORD
     *
     * @mbg.generated
     */
    public void setStudentPassword(String studentPassword) {
        this.studentPassword = studentPassword == null ? null : studentPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT_INFO.DEPARMENT
     *
     * @return the value of STUDENT_INFO.DEPARMENT
     *
     * @mbg.generated
     */
    public String getDeparment() {
        return deparment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT_INFO.DEPARMENT
     *
     * @param deparment the value for STUDENT_INFO.DEPARMENT
     *
     * @mbg.generated
     */
    public void setDeparment(String deparment) {
        this.deparment = deparment == null ? null : deparment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT_INFO.CLASS
     *
     * @return the value of STUDENT_INFO.CLASS
     *
     * @mbg.generated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT_INFO.CLASS
     *
     * @param class the value for STUDENT_INFO.CLASS
     *
     * @mbg.generated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT_INFO.SCORE
     *
     * @return the value of STUDENT_INFO.SCORE
     *
     * @mbg.generated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT_INFO.SCORE
     *
     * @param score the value for STUDENT_INFO.SCORE
     *
     * @mbg.generated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_INFO
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentName=").append(studentName);
        sb.append(", studentPassword=").append(studentPassword);
        sb.append(", deparment=").append(deparment);
        sb.append(", grade=").append(grade);
        sb.append(", score=").append(score);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}