package com.zy.atsm.entity;

import java.io.Serializable;

public class TeacherInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER_INFO.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER_INFO.TEACHER_PASSWORD
     *
     * @mbg.generated
     */
    private String teacherPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER_INFO.TEACHER_NAME
     *
     * @mbg.generated
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER_INFO.PROJECT_ID
     *
     * @mbg.generated
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TEACHER_INFO
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER_INFO.ID
     *
     * @return the value of TEACHER_INFO.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER_INFO.ID
     *
     * @param id the value for TEACHER_INFO.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER_INFO.TEACHER_PASSWORD
     *
     * @return the value of TEACHER_INFO.TEACHER_PASSWORD
     *
     * @mbg.generated
     */
    public String getTeacherPassword() {
        return teacherPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER_INFO.TEACHER_PASSWORD
     *
     * @param teacherPassword the value for TEACHER_INFO.TEACHER_PASSWORD
     *
     * @mbg.generated
     */
    public void setTeacherPassword(String teacherPassword) {
        this.teacherPassword = teacherPassword == null ? null : teacherPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER_INFO.TEACHER_NAME
     *
     * @return the value of TEACHER_INFO.TEACHER_NAME
     *
     * @mbg.generated
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER_INFO.TEACHER_NAME
     *
     * @param teacherName the value for TEACHER_INFO.TEACHER_NAME
     *
     * @mbg.generated
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER_INFO.PROJECT_ID
     *
     * @return the value of TEACHER_INFO.PROJECT_ID
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER_INFO.PROJECT_ID
     *
     * @param projectId the value for TEACHER_INFO.PROJECT_ID
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER_INFO
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", teacherPassword=").append(teacherPassword);
        sb.append(", teacherName=").append(teacherName);
        sb.append(", projectId=").append(projectId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}